package com.example.liuqu.Controller;

import com.example.liuqu.Model.Result;
import com.example.liuqu.Model.User;
import com.example.liuqu.Repository.UserRepository;
import com.example.liuqu.service.userService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/liuqu") // This means URL's start with /demo (after Application path)
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private userService userService;
    private UserRepository userRepository;


    @PostMapping(value = "/register", consumes = { "multipart/form-data" })
    public ResponseEntity<Result> register(User user) {
        Result result = userService.register(user);
        return new ResponseEntity<>(result, HttpStatus.OK);

    }

    @PostMapping("/login")
    public ResponseEntity<Result> login(@RequestParam String emailOrPhone, @RequestParam String password) {
        Result result = userService.login(emailOrPhone,password);
        return new ResponseEntity<>(result, HttpStatus.OK);
    }

    @PostMapping("/change-password")
    public ResponseEntity<String> changePassword(@RequestParam Integer uid, @RequestParam String token, @RequestParam String newPassword) {
        userService.changePassword(uid, token, newPassword);
        return ResponseEntity.ok("Password changed successfully");
    }

}